// <auto-generated />
using System;
using ConsultaRUCAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsultaRUCAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250723191155_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConsultaRUCAPI.Models.Persona", b =>
                {
                    b.Property<string>("PASS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PERFIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("th_ciu_id")
                        .HasColumnType("int");

                    b.Property<int?>("th_parr_id")
                        .HasColumnType("int");

                    b.Property<string>("th_per_actividad_economica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_agente_retencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_canton")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_clase_contribuyente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_codigo_ciiu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_codigo_jurisdiccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_codigo_sap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_especial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("th_per_estado")
                        .HasColumnType("smallint");

                    b.Property<string>("th_per_estado_civil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_estado_contribuyente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_estado_establecimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("th_per_fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("th_per_fecha_hora_actualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("th_per_fecha_hora_inicio_actividades")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("th_per_fecha_hora_reinicio_actividades")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("th_per_fecha_hora_suspension_definitiva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("th_per_fecha_modificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("th_per_fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("th_per_foto_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("th_per_id")
                        .HasColumnType("int");

                    b.Property<int?>("th_per_id_comunidad")
                        .HasColumnType("int");

                    b.Property<string>("th_per_nacionalidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_nombre_fantasia_comercial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_numero_establecimiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_obligado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_parroquia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_postal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_primer_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_primer_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_provincia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_razon_social")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_segundo_apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_segundo_nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_tabla")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_tabla_union")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_telefono_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_telefono_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_tipo_contribuyente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("th_per_unidad_org_sap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("th_prov_id")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("ConsultaRUCAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
